### ISSUE TITLE
nested views not being cleaned up on transition

### ISSUE THREAD

**Issue by airtonix** [inca/voie#12] opened 2016-01-27 03:17 UTC
I started creating a example of this problem on jsbin, however I need a CDN build of your library to complete it.

Tried using the umd module transform of babel, but no luck in resulting a single file i could use on something like jsfiddle/jsbin/codepen.

https://jsfiddle.net/z6rpybbd/7/

**Comment by airtonix** [comment] 2016-01-27 07:02
appears there may be a limit to how many nested vues can contain `v-view`.

I just reduced to down from this:
```
root: (template with v-view)
  root.auction: (template with v-view)
    root.auction.create: (template with v-view)
      root.auction.create.one: (template)
      root.auction.create.two: (template)
      ...
    root.auction.detail: (template)
  root.auth: (template)
```

to this"

```
root: (template with v-view)
  root.create: (template with v-view)
    root.create.one: (template)
    root.create.two: (template)
    ...
  root.detail: (template)
  root.auth: (template)
```

Although I'm not sure if this matters, but coming from Angular, I wrapped my view templates in one single parent html element:

```
<template>
  <div>
    <h1>Login</h1>
    <form> ... </form>
  </div>
</template>

**Comment by inca** [comment] 2016-01-27 15:18
Just to clarify, does Vue `<template>` contain multiple child elements in your case? If so, then it falls under [fragment instance](http://vuejs.org/guide/components.html#Fragment_Instance) category and will not work properly (in other words, you should always have a single-element components).

**Comment by airtonix** [comment] 2016-01-30 00:06
Yeah even after ensuring the `<template>` tags in my state views had only one child element, I found that moving from any state under `root.auction.create.*` to any other state would result in the source state markup not being cleaned up.

Perhaps karma tests that explore this may shed light on what is going on?

**Comment by inca** [comment] 2016-01-30 07:44
So do you think depth is the issue?

Also, could you please provide some debugging info about this? Enable debug logging by typing `localStorage.debug = 'voie*'`, then refresh the page, go to one of `root.auction.create` descendants and perform navigation outside. Then paste logs or SS here so that we could see what's actually going on there. Thanks!

**Comment by inca** [comment] 2016-02-11 13:42
Still don't know what the issue is. Closing this, please feel free to reopen when more information is gathered.

**Closed by inca** 2016-02-11 13:42 UTC

**Comment by airtonix** [comment] 2016-03-03 04:04
It was because my root element was a fragment.

so the rule is:
- one child element, which can't be a fragment: http://vuejs.org/guide/components.html#Fragment_Instance
